import React, { useState, useEffect, useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Navbar, BottomProgressBar } from '../components/layout';
import { useProgressStep } from '../hooks/useProgressStep';
import { RDSensitivityPlot, RDScatterPlot } from '../components/charts';
import { aiService, ResultsInterpretation } from '../services/aiService';
import { useAuth } from '../contexts/AuthContext';
import { projectStateService } from '../services/projectStateService';

const COLLAPSE_THRESHOLD = 200;
const MAX_MESSAGE_LENGTH = 2000;

const RDResults: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { accessToken } = useAuth();
  const { currentStep, steps, goToPreviousStep, goToNextStep, navigateToStep } = useProgressStep();
  const [results, setResults] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [aiInterpretation, setAiInterpretation] = useState<ResultsInterpretation | null>(null);
  const [loadingAI, setLoadingAI] = useState(false);
  const [aiError, setAiError] = useState<string | null>(null);
  const [aiSidebarWidth, setAiSidebarWidth] = useState(480);
  const [isResizing, setIsResizing] = useState(false);
  const [isAiSidebarCollapsed, setIsAiSidebarCollapsed] = useState(false);
  const [chatMessages, setChatMessages] = useState<Array<{ role: 'user' | 'assistant'; content: string; timestamp?: string }>>([]);
  const [chatInput, setChatInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const [chatError, setChatError] = useState<string | null>(null);
  const [datasetInfo, setDatasetInfo] = useState<any>(null);
  const [expandedStat, setExpandedStat] = useState<'ci' | 'pvalue' | 'se' | null>(null);
  const [showCode, setShowCode] = useState(false);
  const [codeLanguage, setCodeLanguage] = useState<'python' | 'r'>('python');
  const [showAssumptions, setShowAssumptions] = useState(false);
  const [activeAssumption, setActiveAssumption] = useState<'continuity' | 'manipulation' | 'late'>('continuity');
  const [showDesignType, setShowDesignType] = useState(false);
  const [recommendedQuestions] = useState<string[]>([
    'What is the local continuity assumption in RD?',
    'How do I interpret my RD estimate?',
    'What are the limitations of this analysis?',
  ]);

  // Generate Python code for RD analysis
  const generatePythonCode = () => {
    if (!results?.parameters) return '';
    const p = results.parameters;
    const res = results.results || {};
    const polyOrder = res.polynomial_order || 1;
    const bwUsed = res.bandwidth_used ? res.bandwidth_used.toFixed(4) : 'None';
    return `# Regression Discontinuity Design Analysis
# Generated by Causal Platform
# Install dependencies: pip install rdrobust rddensity statsmodels pandas numpy matplotlib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# rdrobust and rddensity — Calonico, Cattaneo & Titiunik (2014)
from rdrobust import rdrobust, rdbwselect, rdplot
from rddensity import rddensity

# ── Load your data ────────────────────────────────────────────────────────────
# df = pd.read_csv('your_data.csv')

# ── Variable definitions ──────────────────────────────────────────────────────
running_var     = '${p.running_var}'
outcome_var     = '${p.outcome_var}'
cutoff          = ${p.cutoff}
treatment_side  = '${p.treatment_side}'  # 'above' means units >= cutoff are treated
polynomial_order = ${polyOrder}

# ── Center the running variable at the cutoff ─────────────────────────────────
df['running_centered'] = df[running_var] - cutoff
df['treated'] = (
    (df[running_var] >= cutoff).astype(int)
    if treatment_side == 'above'
    else (df[running_var] < cutoff).astype(int)
)

# ── Step 1: Optimal bandwidth selection (MSE-optimal) ────────────────────────
bw_sel = rdbwselect(df[outcome_var], df['running_centered'],
                    kernel='triangular', bwselect='mserd')
bw_opt = bw_sel.bws['h'][0]
print(f"Optimal MSE bandwidth: {bw_opt:.4f}")

# ── Step 2: Main RD estimate (conventional + robust bias-corrected CI) ────────
rdd = rdrobust(df[outcome_var], df['running_centered'],
               c=0,
               kernel='triangular',
               bwselect='mserd',
               p=${polyOrder},
               h=${bwUsed})   # set to bw_opt for automatic, or use fixed bandwidth
rdd.summary()
print(f"\\nLocal polynomial order: ${polyOrder}")
print(f"Bandwidth used:          {rdd.bws['h'][0]:.4f} (left), {rdd.bws['h'][1]:.4f} (right)")
print(f"Observations in window:  {rdd.N[2]:.0f} (left) + {rdd.N[3]:.0f} (right)")
print(f"\\nTreatment Effect (conventional): {rdd.coef[0]:.4f}")
print(f"Treatment Effect (bias-corrected): {rdd.coef[1]:.4f}")
print(f"Robust 95% CI:  [{rdd.ci[2, 0]:.4f}, {rdd.ci[2, 1]:.4f}]")
print(f"Robust p-value: {rdd.pv[2]:.4f}")

# ── Step 3: RD visualization ─────────────────────────────────────────────────
rdplot(df[outcome_var], df['running_centered'],
       c=0, p=${polyOrder},
       x_label='${p.running_var} (centered at cutoff ${p.cutoff})',
       y_label='${p.outcome_var}',
       title='Regression Discontinuity Plot')
plt.savefig('rd_plot.png', dpi=300, bbox_inches='tight')
plt.show()

# ── Step 4: Manipulation test (McCrary/Rddensity) ────────────────────────────
# Tests for bunching around the cutoff (strategic sorting)
density_test = rddensity(df['running_centered'])
density_test.summary()
print("\\nManipulation test: if p < 0.05, units may be sorting around the cutoff")

# ── Step 5: Sensitivity to bandwidth choice ───────────────────────────────────
print("\\n=== BANDWIDTH SENSITIVITY ===")
multipliers = [0.5, 0.75, 1.0, 1.25, 1.5]
rows = []
for mult in multipliers:
    bw = bw_opt * mult
    try:
        fit = rdrobust(df[outcome_var], df['running_centered'],
                       c=0, h=bw, p=${polyOrder})
        rows.append({
            'bandwidth_mult': mult,
            'bandwidth': round(bw, 4),
            'estimate':  round(fit.coef[0], 4),
            'robust_ci_lo': round(fit.ci[2, 0], 4),
            'robust_ci_hi': round(fit.ci[2, 1], 4),
            'p_value':   round(fit.pv[2], 4),
        })
    except Exception as e:
        print(f"  bandwidth={bw:.4f}: failed ({e})")

print(pd.DataFrame(rows).to_string(index=False))

# ── Step 6: Covariate balance check at cutoff (placebo test) ─────────────────
# If you have pre-treatment covariates, test that they DON'T jump at the cutoff
# Replace 'covariate1', 'covariate2' with actual covariate column names
# for cov in ['covariate1', 'covariate2']:
#     cov_test = rdrobust(df[cov], df['running_centered'], c=0, p=${polyOrder})
#     print(f"{cov}: effect={cov_test.coef[0]:.4f}, p={cov_test.pv[2]:.4f}")`;
  };

  // Generate R code for RD analysis
  const generateRCode = () => {
    if (!results?.parameters) return '';
    const p = results.parameters;
    const res = results.results || {};
    const polyOrder = res.polynomial_order || 1;
    const bwUsed = res.bandwidth_used ? res.bandwidth_used.toFixed(4) : 'NULL';
    return `# Regression Discontinuity Design Analysis
# Generated by Causal Platform
# Install: install.packages(c("rdrobust", "rddensity", "tidyverse", "ggplot2"))

library(tidyverse)
library(rdrobust)
library(rddensity)
library(ggplot2)

# ── Load your data ────────────────────────────────────────────────────────────
# df <- read.csv("your_data.csv")

# ── Variable definitions ──────────────────────────────────────────────────────
running_var      <- "${p.running_var}"
outcome_var      <- "${p.outcome_var}"
cutoff           <- ${p.cutoff}
treatment_side   <- "${p.treatment_side}"   # "above" = units >= cutoff are treated
polynomial_order <- ${polyOrder}

# ── Center the running variable at the cutoff ─────────────────────────────────
df <- df %>%
  mutate(
    running_centered = .data[[running_var]] - cutoff,
    treated = if (treatment_side == "above")
                as.integer(.data[[running_var]] >= cutoff)
              else
                as.integer(.data[[running_var]] < cutoff)
  )

# ── Step 1: Optimal bandwidth selection ──────────────────────────────────────
bw_sel <- rdbwselect(df[[outcome_var]], df$running_centered,
                     kernel = "triangular", bwselect = "mserd")
bw_opt <- bw_sel$bws["h", "left"]
cat(sprintf("Optimal MSE bandwidth: %.4f\\n", bw_opt))

# ── Step 2: Main RD estimate ─────────────────────────────────────────────────
rdd <- rdrobust(df[[outcome_var]], df$running_centered,
                c = 0,
                kernel = "triangular",
                bwselect = "mserd",
                p = polynomial_order,
                h = ${bwUsed})   # set to NULL for automatic, or fixed bandwidth
summary(rdd)

cat(sprintf("\\nLocal polynomial order:    %d\\n", polynomial_order))
cat(sprintf("Bandwidth used:             %.4f\\n", rdd$bws["h", "left"]))
cat(sprintf("\\nTreatment Effect (conv.):  %.4f\\n", rdd$coef[1]))
cat(sprintf("Treatment Effect (bc):      %.4f\\n", rdd$coef[2]))
cat(sprintf("Robust 95%% CI:             [%.4f, %.4f]\\n",
            rdd$ci[3, 1], rdd$ci[3, 2]))
cat(sprintf("Robust p-value:             %.4f\\n", rdd$pv[3]))

# ── Step 3: RD plot (rdrobust) ────────────────────────────────────────────────
rdplot(df[[outcome_var]], df$running_centered,
       c = 0, p = polynomial_order,
       x.label = paste0(running_var, " (centered at cutoff ${p.cutoff})"),
       y.label = outcome_var,
       title   = "Regression Discontinuity Design")

# ── Step 4: ggplot2 version with raw data ─────────────────────────────────────
df_win <- df %>% filter(abs(running_centered) <= bw_opt * 1.5)

ggplot(df_win,
       aes(x = running_centered, y = .data[[outcome_var]],
           color = factor(treated))) +
  geom_point(alpha = 0.4, size = 1.2) +
  geom_smooth(aes(group = factor(treated)),
              method = "lm",
              formula = y ~ poly(x, polynomial_order),
              se = TRUE, linewidth = 1.2) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", linewidth = 1) +
  scale_color_manual(values = c("0" = "#FF6B6B", "1" = "#4F9CF9"),
                     labels = c("0" = "Control (${
                       p.treatment_side === 'above' ? 'below' : 'above'
                     } cutoff)",
                                "1" = "Treatment (${
                                  p.treatment_side === 'above' ? 'above' : 'below'
                                } cutoff)")) +
  labs(
    title    = "Regression Discontinuity Design",
    subtitle = paste0("Running variable: ${p.running_var}  |  Cutoff = ${p.cutoff}"),
    x        = paste0("${p.running_var} (centered at cutoff)"),
    y        = "${p.outcome_var}",
    color    = "Group"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")

ggsave("rd_plot.png", width = 10, height = 6, dpi = 300)

# ── Step 5: Manipulation test (McCrary / rddensity) ───────────────────────────
density_test <- rddensity(df$running_centered)
summary(density_test)
cat("\\nIf p < 0.05, units may be sorting strategically around the cutoff\\n")

# ── Step 6: Bandwidth sensitivity ─────────────────────────────────────────────
cat("\\n=== BANDWIDTH SENSITIVITY ===\\n")
multipliers <- c(0.5, 0.75, 1.0, 1.25, 1.5)
sensitivity <- purrr::map_dfr(multipliers, function(mult) {
  bw <- bw_opt * mult
  tryCatch({
    fit <- rdrobust(df[[outcome_var]], df$running_centered,
                    c = 0, h = bw, p = polynomial_order)
    tibble(bandwidth_mult = mult,
           bandwidth      = round(bw, 4),
           estimate       = round(fit$coef[1], 4),
           robust_ci_lo   = round(fit$ci[3, 1], 4),
           robust_ci_hi   = round(fit$ci[3, 2], 4),
           p_value        = round(fit$pv[3], 4))
  }, error = function(e) NULL)
})
print(sensitivity)

# ── Step 7: Covariate balance check (placebo test) ────────────────────────────
# Replace with actual pre-treatment covariate names to verify no jump at cutoff
# covariates <- c("age", "income_pre")
# for (cov in covariates) {
#   cov_test <- rdrobust(df[[cov]], df$running_centered, c = 0, p = polynomial_order)
#   cat(sprintf("%s: effect=%.4f, p=%.4f\\n", cov, cov_test$coef[1], cov_test$pv[3]))
# }`;
  };

  const chatMessagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const loadResults = async () => {
      const projectId =
        (location.state as any)?.projectId ||
        parseInt(new URLSearchParams(location.search).get('projectId') || '0') ||
        null;

      let loadedResults: any = null;

      // 1. Try project state (backend) - source of truth per project
      if (projectId && accessToken) {
        try {
          const project = await projectStateService.loadProject(projectId, accessToken);
          if (project.lastResults?.results && project.lastResults?.parameters) {
            loadedResults = project.lastResults;
          }
        } catch (err) {
          console.warn('Failed to load RD results from project state:', err);
        }
      }

      // 2. Try localStorage keyed by project
      if (!loadedResults && projectId) {
        const stored = localStorage.getItem(`rdAnalysisResults_${projectId}`);
        if (stored) {
          try {
            loadedResults = JSON.parse(stored);
          } catch (e) {
            console.warn('Failed to parse project RD results from localStorage:', e);
          }
        }
      }

      // 3. Fallback: legacy global key (for backwards compatibility when no projectId)
      if (!loadedResults) {
        const stored = localStorage.getItem('rdAnalysisResults');
        if (stored) {
          try {
            loadedResults = JSON.parse(stored);
          } catch (e) {
            console.warn('Failed to parse RD results from localStorage:', e);
          }
        }
      }

      if (loadedResults) {
        setResults(loadedResults);

        // Load cached AI interpretation if it matches this analysis
        const interpretationKey = projectId
          ? `rdAiInterpretation_${projectId}`
          : 'rdAiInterpretation';
        const storedInterpretation = localStorage.getItem(interpretationKey);
        if (storedInterpretation) {
          try {
            const parsed = JSON.parse(storedInterpretation);
            const params = loadedResults.parameters || {};
            const currentKey = JSON.stringify({
              dataset_id: loadedResults.dataset_id,
              running_var: params.running_var,
              outcome_var: params.outcome_var,
              cutoff: params.cutoff,
              treatment_effect: loadedResults.results?.treatment_effect,
              p_value: loadedResults.results?.p_value,
            });
            if (parsed.analysisKey === currentKey) {
              setAiInterpretation(parsed.interpretation);
            } else {
              localStorage.removeItem(interpretationKey);
            }
          } catch {
            localStorage.removeItem(interpretationKey);
          }
        }
      } else {
        setAiInterpretation(null);
      }
      setLoading(false);
    };

    loadResults();
  }, [accessToken, location.state, location.search]);

  const loadAIInterpretation = async () => {
    if (!results?.results || !results?.parameters) {
      setAiError('Results or parameters not available');
      return;
    }

    setLoadingAI(true);
    setAiError(null);

    try {
      const interpretation = await aiService.interpretResults(
        results.results,
        results.parameters,
        undefined,
        'Regression Discontinuity'
      );
      setAiInterpretation(interpretation);

      const params = results.parameters || {};
      const analysisKey = JSON.stringify({
        dataset_id: results.dataset_id,
        running_var: params.running_var,
        outcome_var: params.outcome_var,
        cutoff: params.cutoff,
        treatment_effect: results.results?.treatment_effect,
        p_value: results.results?.p_value,
      });
      const projectId =
        (location.state as any)?.projectId ||
        parseInt(new URLSearchParams(location.search).get('projectId') || '0') ||
        null;
      const interpretationKey = projectId ? `rdAiInterpretation_${projectId}` : 'rdAiInterpretation';
      localStorage.setItem(interpretationKey, JSON.stringify({
        analysisKey,
        interpretation,
        timestamp: new Date().toISOString(),
      }));
    } catch (error: any) {
      const errorData = error.response?.data;
      const errorMessage = errorData?.error || error.message || 'Failed to get AI interpretation';
      setAiError(errorMessage);
    } finally {
      setLoadingAI(false);
    }
  };

  // Load dataset info for chat context
  useEffect(() => {
    const loadDatasetInfo = async () => {
      const datasetId = results?.dataset_id || (location.state as any)?.datasetId;
      const projectId = (location.state as any)?.projectId;
      if (!datasetId || !accessToken) return;

      try {
        const axios = (await import('axios')).default;
        if (projectId) {
          const projectResponse = await axios.get(`/projects/${projectId}/datasets`, {
            headers: { Authorization: `Bearer ${accessToken}` },
          });
          const datasets = projectResponse.data.datasets || [];
          const dataset = datasets.find((d: any) => d.id === datasetId);
          if (dataset) {
            try {
              const previewResponse = await axios.get(`/datasets/${datasetId}/preview`, {
                headers: { Authorization: `Bearer ${accessToken}` },
              });
              setDatasetInfo({
                name: dataset.name,
                columns: previewResponse.data.columns || [],
                summary: previewResponse.data.summary || {},
              });
            } catch {
              setDatasetInfo({ name: dataset.name, columns: [], summary: {} });
            }
          }
        } else {
          try {
            const previewResponse = await axios.get(`/datasets/${datasetId}/preview`, {
              headers: { Authorization: `Bearer ${accessToken}` },
            });
            setDatasetInfo({
              name: undefined,
              columns: previewResponse.data.columns || [],
              summary: previewResponse.data.summary || {},
            });
          } catch {
            setDatasetInfo(null);
          }
        }
      } catch (error) {
        console.error('Error loading dataset info:', error);
      }
    };

    if (results) loadDatasetInfo();
  }, [results, accessToken, location.state]);

  // Scroll chat to bottom
  useEffect(() => {
    chatMessagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  // Resize handlers for AI sidebar
  useEffect(() => {
    let lastWidth = aiSidebarWidth;

    const handleMouseMove = (e: MouseEvent) => {
      if (!isResizing) return;
      const container = document.querySelector('[data-rd-main-layout]') as HTMLElement;
      if (!container) return;
      const containerRect = container.getBoundingClientRect();
      const newWidth = containerRect.right - e.clientX;
      const minWidth = COLLAPSE_THRESHOLD;
      const maxWidth = 800;
      const constrainedWidth = Math.max(minWidth, Math.min(maxWidth, newWidth));
      lastWidth = constrainedWidth;
      if (constrainedWidth <= COLLAPSE_THRESHOLD) {
        setIsAiSidebarCollapsed(true);
      } else {
        setIsAiSidebarCollapsed(false);
        setAiSidebarWidth(constrainedWidth);
      }
    };

    const handleMouseUp = () => {
      setIsResizing(false);
      if (lastWidth <= COLLAPSE_THRESHOLD) setIsAiSidebarCollapsed(true);
    };

    if (isResizing) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    };
  }, [isResizing, aiSidebarWidth]);

  const handleResizeStart = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsResizing(true);
  };

  const handleOpenAiSection = () => {
    setIsAiSidebarCollapsed(false);
    // Always reset width when reopening: after drag-collapse, aiSidebarWidth is never
    // updated (setAiSidebarWidth is only called when constrainedWidth > COLLAPSE_THRESHOLD),
    // so aiSidebarWidth <= COLLAPSE_THRESHOLD would never pass. Reset to default.
    setAiSidebarWidth(480);
  };

  const handleSendMessage = async () => {
    const message = chatInput.trim();
    if (!message || chatLoading) return;
    if (message.length > MAX_MESSAGE_LENGTH) {
      setChatError(`Message too long. Maximum ${MAX_MESSAGE_LENGTH} characters allowed.`);
      return;
    }

    setChatError(null);
    setChatLoading(true);
    const userMessage = { role: 'user' as const, content: message, timestamp: new Date().toISOString() };
    setChatMessages((prev) => [...prev, userMessage]);
    setChatInput('');

    try {
      const conversationHistory = chatMessages.map((msg) => ({ role: msg.role, content: msg.content }));
      const analysisContext = results
        ? {
            parameters: results.parameters,
            results: results.results,
            ai_interpretation: aiInterpretation || undefined,
          }
        : undefined;

      const response = await aiService.chat(
        message,
        conversationHistory,
        analysisContext,
        datasetInfo
      );

      const assistantMessage = {
        role: 'assistant' as const,
        content: response.response,
        timestamp: response.timestamp,
      };
      setChatMessages((prev) => [...prev, assistantMessage]);
    } catch (error: any) {
      console.error('Chat error:', error);
      setChatError(error.response?.data?.error || error.message || 'Failed to send message');
      setChatMessages((prev) => prev.slice(0, -1));
    } finally {
      setChatLoading(false);
    }
  };

  const handleChatInputKeyPress = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  if (loading) {
    return (
      <div>
        <Navbar />
        <div style={styles.loadingContainer}>
          <div style={styles.loadingSpinner}></div>
          <p style={styles.loadingText}>Loading results...</p>
        </div>
      </div>
    );
  }

  if (!results || !results.results) {
    return (
      <div>
        <Navbar />
        <div style={styles.errorContainer}>
          <h2 style={styles.errorTitle}>No Results Found</h2>
          <p style={styles.errorMessage}>
            No analysis results available. Please run an analysis first.
          </p>
          <button
            onClick={() => navigate('/method-selection')}
            style={styles.backButton}
          >
            Go to Method Selection
          </button>
        </div>
      </div>
    );
  }

  const { results: res, parameters, bandwidth_info } = results;
  const isSignificant = res.p_value < 0.05;
  const rdType: 'sharp' | 'fuzzy' = (res.rd_type === 'fuzzy' || parameters.rd_type === 'fuzzy') ? 'fuzzy' : 'sharp';
  const isFuzzy = rdType === 'fuzzy';
  const DesignBadge = () => (
    <span style={isFuzzy ? styles.fuzzyBadge : styles.sharpBadge}>
      {isFuzzy ? 'Fuzzy RDD' : 'Sharp RDD'}
    </span>
  );

  return (
    <div>
      <Navbar />
      <div style={styles.contentContainer}>
        <div
          data-rd-main-layout
          style={{
            ...styles.mainLayout,
            justifyContent: isAiSidebarCollapsed ? 'center' : 'flex-start',
            gap: isAiSidebarCollapsed ? '24px' : '48px',
            position: 'relative' as const,
          }}
        >
          {/* Main Content */}
          <div
            style={{
              ...styles.mainContent,
              flex: isAiSidebarCollapsed ? '1 1 auto' : '1 1 60%',
              minWidth: isAiSidebarCollapsed ? 'auto' : '60%',
              maxWidth: isAiSidebarCollapsed ? '1200px' : 'none',
              margin: isAiSidebarCollapsed ? '0 auto' : '0',
            }}
          >
        <div style={styles.header}>
          <h1 style={styles.title}>Regression Discontinuity Results</h1>
          <p style={styles.subtitle}>
            Analysis complete for {parameters.running_var} at cutoff {parameters.cutoff}
          </p>
        </div>

        <div style={styles.content}>
          {/* Main Result Card */}
          <div style={styles.mainResultCard}>
            <h2 style={styles.resultLabel}>Treatment Effect</h2>
            <div style={styles.effectValue}>
              {res.treatment_effect.toFixed(3)}
            </div>
            <div
              style={{
                ...styles.significanceBadge,
                ...(isSignificant
                  ? styles.significantBadge
                  : styles.notSignificantBadge),
              }}
            >
              {isSignificant ? '✓ Statistically Significant' : 'Not Statistically Significant'}
            </div>
            {/* 95% CI, P-Value, and Standard Error in one row; one explanation box below */}
            <div style={styles.statsRow}>
              <div style={styles.statRowItem}>
                <span style={styles.statRowLabel}>95% CI</span>
                <span style={{ ...styles.statRowValue, fontFamily: 'monospace' }}>
                  [{res.ci_lower.toFixed(3)}, {res.ci_upper.toFixed(3)}]
                </span>
                <button
                  type="button"
                  onClick={() => setExpandedStat((s) => (s === 'ci' ? null : 'ci'))}
                  style={expandedStat === 'ci' ? styles.expandButtonActive : styles.expandButton}
                >
                  {expandedStat === 'ci' ? '▼ Hide' : '▶ How is this derived?'}
                </button>
              </div>
              <div style={styles.statRowItem}>
                <span style={styles.statRowLabel}>P-Value</span>
                <span style={styles.statRowValue}>{res.p_value.toFixed(4)}</span>
                <button
                  type="button"
                  onClick={() => setExpandedStat((s) => (s === 'pvalue' ? null : 'pvalue'))}
                  style={expandedStat === 'pvalue' ? styles.expandButtonActive : styles.expandButton}
                >
                  {expandedStat === 'pvalue' ? '▼ Hide' : '▶ How is this derived?'}
                </button>
              </div>
              <div style={styles.statRowItem}>
                <span style={styles.statRowLabel}>Standard Error</span>
                <span style={styles.statRowValue}>{res.se.toFixed(3)}</span>
                <button
                  type="button"
                  onClick={() => setExpandedStat((s) => (s === 'se' ? null : 'se'))}
                  style={expandedStat === 'se' ? styles.expandButtonActive : styles.expandButton}
                >
                  {expandedStat === 'se' ? '▼ Hide' : '▶ How is this derived?'}
                </button>
              </div>
            </div>
            {expandedStat && (
              <div style={styles.singleExplanationBox}>
                {expandedStat === 'ci' && (
                  <p style={styles.singleExplanationText}>
                    A 95% confidence interval (CI) is the range of values within which we are 95% confident the true treatment effect lies. If the interval does not include zero, the effect is typically considered statistically significant at the 5% level.
                  </p>
                )}
                {expandedStat === 'pvalue' && (
                  <p style={styles.singleExplanationText}>
                    The p-value tests the null hypothesis that the true treatment effect is zero. It is derived from the t-statistic: t = (treatment effect − 0) / SE. In this study: t = {res.treatment_effect.toFixed(3)} / {res.se.toFixed(3)} ≈ {(res.treatment_effect / res.se).toFixed(2)}. The p-value of {res.p_value.toFixed(4)} is the probability of observing |t| at least this large when the true effect is zero (from the local polynomial regression). A p-value below 0.05 is typically considered statistically significant.
                  </p>
                )}
                {expandedStat === 'se' && (
                  <p style={styles.singleExplanationText}>
                    The standard error (SE) for this study is {res.se.toFixed(3)}. It was computed from the local polynomial regression (order {res.polynomial_order}) with bandwidth {res.bandwidth_used.toFixed(3)}, using robust standard errors. The 95% CI is then: effect ± 1.96 × SE = {res.treatment_effect.toFixed(3)} ± 1.96 × {res.se.toFixed(3)} = [{res.ci_lower.toFixed(3)}, {res.ci_upper.toFixed(3)}]. A smaller SE means a more precise estimate.
                  </p>
                )}
              </div>
            )}
          </div>

          {/* ── Fuzzy RDD: First-Stage Compliance Card ── */}
          {isFuzzy && (
            <div style={styles.fuzzyCard}>
              <h3 style={styles.fuzzyCardTitle}>First-Stage Compliance Diagnostics</h3>
              <p style={{ fontSize: '14px', color: '#555', margin: '0 0 16px 0', lineHeight: 1.5 }}>
                In Fuzzy RDD, the estimate is valid only if the cutoff causes a meaningful jump in treatment receipt. The table below shows the first-stage diagnostics.
              </p>
              <div style={styles.fuzzyGrid}>
                <div style={styles.fuzzyStatBox}>
                  <div style={styles.fuzzyStatLabel}>LATE (Fuzzy Estimate)</div>
                  <div style={styles.fuzzyStatValue}>{res.treatment_effect.toFixed(3)}</div>
                  <div style={styles.fuzzyStatNote}>Intent-to-treat ÷ first-stage compliance</div>
                </div>
                <div style={styles.fuzzyStatBox}>
                  <div style={styles.fuzzyStatLabel}>Intent-to-Treat Effect</div>
                  <div style={styles.fuzzyStatValue}>{res.reduced_form_effect != null ? res.reduced_form_effect.toFixed(3) : '—'}</div>
                  <div style={styles.fuzzyStatNote}>Jump in {parameters.outcome_var} at cutoff (reduced form)</div>
                </div>
                <div style={styles.fuzzyStatBox}>
                  <div style={styles.fuzzyStatLabel}>First-Stage Effect</div>
                  <div style={styles.fuzzyStatValue}>
                    {res.first_stage_effect != null ? res.first_stage_effect.toFixed(3) : '—'}
                  </div>
                  <div style={styles.fuzzyStatNote}>Jump in treatment receipt at cutoff</div>
                </div>
                <div style={styles.fuzzyStatBox}>
                  <div style={styles.fuzzyStatLabel}>Compliance — Assigned</div>
                  <div style={styles.fuzzyStatValue}>
                    {res.compliance_rate_assigned != null ? (res.compliance_rate_assigned * 100).toFixed(1) + '%' : '—'}
                  </div>
                  <div style={styles.fuzzyStatNote}>Treatment receipt rate for units {parameters.treatment_side === 'above' ? 'at/above' : 'below'} cutoff</div>
                </div>
                <div style={styles.fuzzyStatBox}>
                  <div style={styles.fuzzyStatLabel}>Compliance — Not Assigned</div>
                  <div style={styles.fuzzyStatValue}>
                    {res.compliance_rate_not_assigned != null ? (res.compliance_rate_not_assigned * 100).toFixed(1) + '%' : '—'}
                  </div>
                  <div style={styles.fuzzyStatNote}>Treatment receipt rate for units {parameters.treatment_side === 'above' ? 'below' : 'at/above'} cutoff</div>
                </div>
                <div style={styles.fuzzyStatBox}>
                  <div style={styles.fuzzyStatLabel}>Treatment Variable</div>
                  <div style={{ ...styles.fuzzyStatValue, fontSize: '15px' }}>{parameters.treatment_var || '—'}</div>
                  <div style={styles.fuzzyStatNote}>Actual receipt indicator used</div>
                </div>
              </div>
              {res.first_stage_effect != null && Math.abs(res.first_stage_effect) < 0.05 && (
                <div style={{ marginTop: '14px', padding: '12px 14px', backgroundColor: '#fff3cd', borderRadius: '8px', border: '1px solid #ffc107', fontSize: '13px', color: '#856404' }}>
                  ⚠ <strong>Weak first stage:</strong> The jump in treatment receipt at the cutoff is very small ({res.first_stage_effect.toFixed(3)}). A weak first stage amplifies estimation error — the LATE estimate should be interpreted with caution.
                </div>
              )}
            </div>
          )}

          {/* ── Key Assumptions ── */}
          <div style={styles.assumptionsCard}>
            <div style={styles.assumptionsHeader}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <h2 style={styles.assumptionsTitle}>Key Assumptions</h2>
                <DesignBadge />
              </div>
              <button
                type="button"
                onClick={() => setShowAssumptions((s) => !s)}
                style={styles.assumptionsToggle}
              >
                {showAssumptions ? '▲ Hide' : '▼ Show'}
              </button>
            </div>
            <p style={styles.assumptionsSub}>
              RD estimates are only valid when these assumptions hold. Review each one carefully before interpreting your results.
            </p>

            {showAssumptions && (
              <div style={{ marginTop: '20px' }}>
                {/* Tab buttons */}
                <div style={styles.assumptionTabs}>
                  {(
                    [
                      { key: 'continuity', label: 'Continuity' },
                      { key: 'manipulation', label: 'No Manipulation' },
                      { key: 'late', label: 'Local Validity' },
                    ] as const
                  ).map(({ key, label }) => (
                    <button
                      key={key}
                      type="button"
                      onClick={() => setActiveAssumption(key)}
                      style={{
                        ...styles.assumptionTab,
                        ...(activeAssumption === key ? styles.assumptionTabActive : {}),
                      }}
                    >
                      {label}
                    </button>
                  ))}
                </div>

                {/* Continuity */}
                {activeAssumption === 'continuity' && (
                  <div style={styles.assumptionContent}>
                    <h3 style={styles.assumptionContentTitle}>RD Continuity Assumption</h3>
                    <p style={styles.assumptionText}>
                      The core identifying assumption of RDD is <strong>continuity</strong>: had units just below the cutoff not received treatment, their average potential outcome would form a smooth, uninterrupted line through the cutoff point. In other words, nothing else changes abruptly at the cutoff except treatment assignment.
                    </p>
                    <p style={styles.assumptionText}>
                      Since potential outcomes are unobservable, we test a concrete implication: <strong>observable characteristics (covariates) should not jump at the cutoff</strong>. If age, income, gender, or other pre-treatment variables are smooth across {parameters.cutoff}, it supports the assumption that unobservables are smooth too — just like in a randomized experiment where treated and control units are comparable on average.
                    </p>
                    <div style={styles.assumptionTip}>
                      <span>
                        <strong>How to check:</strong> Run placebo RD regressions using your covariates as outcome variables. If none jump significantly at {parameters.cutoff}, the continuity assumption is supported. The code section includes commented covariate balance checks you can run on your own data.
                      </span>
                    </div>
                  </div>
                )}

                {/* No manipulation */}
                {activeAssumption === 'manipulation' && (
                  <div style={styles.assumptionContent}>
                    <h3 style={styles.assumptionContentTitle}>No Manipulation / No Bunching</h3>
                    <p style={styles.assumptionText}>
                      RDD requires that units cannot precisely manipulate their value of <strong>{parameters.running_var}</strong> to sort themselves to the desired side of the cutoff ({parameters.cutoff}). If units can game the system — for example, submitting paperwork in a way that ensures they land just above or just below the threshold — the groups near the cutoff will no longer be comparable.
                    </p>
                    <p style={styles.assumptionText}>
                      A classic warning sign is a suspicious spike or gap in the <strong>density of the running variable exactly at the cutoff</strong>. This is called <em>bunching</em> or <em>sorting</em>. A well-known example: a Colombian welfare program initially showed smooth density around its poverty-score cutoff, but after a few years a sharp cliff appeared as households learned how to report characteristics that kept their score just below the eligibility threshold.
                    </p>
                    <div style={styles.assumptionTip}>
                      <span>
                        <strong>How to check:</strong> Plot a histogram of <em>{parameters.running_var}</em> and look for unusual spikes or gaps at {parameters.cutoff}. Formally, use the <strong>McCrary/rddensity test</strong> — it tests whether the density of the running variable is continuous at the cutoff. The replication code in the section below includes this test (Step 4: Manipulation test).
                      </span>
                    </div>
                    <div style={{ ...styles.assumptionTip, backgroundColor: '#fff3cd', borderColor: '#ffc107', marginTop: '10px' }}>
                      <span>
                        Unlike the continuity assumption, manipulation is directly testable. If the density test rejects (p &lt; 0.05), the RD estimate may be biased and caution is warranted.
                      </span>
                    </div>
                  </div>
                )}

                {/* LATE */}
                {activeAssumption === 'late' && (
                  <div style={styles.assumptionContent}>
                    <h3 style={styles.assumptionContentTitle}>Local Validity — The Estimate is a LATE</h3>
                    <p style={styles.assumptionText}>
                      The treatment effect estimated by RDD is a <strong>Local Average Treatment Effect (LATE)</strong>. It is local in the sense that it only applies to units whose value of <em>{parameters.running_var}</em> is close to the cutoff ({parameters.cutoff}), specifically within the bandwidth of <strong>{res.bandwidth_used?.toFixed(3)}</strong> used in this analysis.
                    </p>
                    <p style={styles.assumptionText}>
                      Units far from the cutoff — those with very high or very low values of {parameters.running_var} — are not part of this comparison and the estimated effect may not generalize to them. This is sometimes called the <em>external validity</em> limitation of RDD.
                    </p>
                    <div style={styles.assumptionTip}>
                      <span>
                        <strong>Practical implication:</strong> Be modest when describing your results. Instead of saying "the treatment affects outcomes in the population," say "the treatment affects outcomes for units near the cutoff of {parameters.cutoff} on {parameters.running_var}." This is not a failure of the design — it is a feature. The local comparison is precisely what makes RDD credible.
                      </span>
                    </div>
                    <div style={{ ...styles.assumptionTip, backgroundColor: '#e8f5e9', borderColor: '#4caf50', marginTop: '10px' }}>
                      <span>
                        The bandwidth sensitivity analysis below shows how the estimate changes as you widen or narrow the window. Stability across bandwidths gives more confidence in the LATE estimate.
                      </span>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* RD Scatter Plot Visualization */}
          <RDScatterPlot
            datasetId={results.dataset_id}
            runningVar={parameters.running_var}
            outcomeVar={parameters.outcome_var}
            cutoff={parameters.cutoff}
            bandwidth={res.bandwidth_used}
            polynomialOrder={res.polynomial_order}
            treatmentSide={parameters.treatment_side}
          />

          {/* Bandwidth Info */}
          <div style={styles.infoCard}>
            <h3 style={styles.infoTitle}>Bandwidth Information</h3>
            <div style={styles.infoGrid}>
              <div style={styles.infoItem}>
                <span style={styles.infoLabel}>Bandwidth Used:</span>
                <span style={styles.infoValue}>{res.bandwidth_used.toFixed(3)}</span>
              </div>
              {bandwidth_info.optimal_bandwidth && (
                <div style={styles.infoItem}>
                  <span style={styles.infoLabel}>Optimal Bandwidth:</span>
                  <span style={styles.infoValue}>
                    {bandwidth_info.optimal_bandwidth.toFixed(3)}
                  </span>
                </div>
              )}
              <div style={styles.infoItem}>
                <span style={styles.infoLabel}>Method:</span>
                <span style={styles.infoValue}>
                  {bandwidth_info.bandwidth_method === 'user_specified'
                    ? 'User Specified'
                    : 'Imbens-Kalyanaraman (2012)'}
                </span>
              </div>
              <div style={styles.infoItem}>
                <span style={styles.infoLabel}>Polynomial Order:</span>
                <span style={styles.infoValue}>{res.polynomial_order === 1 ? 'Linear' : 'Quadratic'}</span>
              </div>
              <div style={styles.infoItem}>
                <span style={styles.infoLabel}>Kernel:</span>
                <span style={styles.infoValue}>Triangular</span>
              </div>
            </div>
            <p style={styles.bandwidthExplanation}>
              <strong>What is bandwidth?</strong> Bandwidth is the distance from the cutoff on the running variable within which observations are used to estimate the discontinuity. A smaller bandwidth uses only units very close to the cutoff (more local, often less bias but higher variance); a larger bandwidth uses more data (smoother estimates but possible bias if the relationship is not linear). The optimal bandwidth balances bias and variance.
            </p>
          </div>

          {/* ── Sharp vs Fuzzy RDD ── */}
          <div style={styles.designTypeCard}>
            <div style={styles.designTypeHeader}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <h3 style={styles.designTypeTitle}>Design Type</h3>
                <DesignBadge />
              </div>
              <button
                type="button"
                onClick={() => setShowDesignType((s) => !s)}
                style={styles.assumptionsToggle}
              >
                {showDesignType ? '▲ Hide' : '▼ Sharp vs Fuzzy'}
              </button>
            </div>
            <p style={{ fontSize: '14px', color: '#555', margin: '6px 0 0 0', lineHeight: 1.5 }}>
              {isFuzzy
                ? <>This analysis uses <strong>Fuzzy RDD</strong>. The cutoff is suggestive — not all units assigned by it actually received treatment. The LATE is estimated as the intent-to-treat effect divided by the first-stage compliance jump (Wald ratio). Treatment receipt variable: <strong>{parameters.treatment_var}</strong>.</>
                : <>This analysis uses <strong>Sharp RDD</strong>, meaning treatment is fully determined by whether {parameters.running_var} is {parameters.treatment_side === 'above' ? 'at or above' : 'below'} the cutoff ({parameters.cutoff}).</>
              }
            </p>

            {showDesignType && (
              <div style={{ marginTop: '20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                {/* Sharp column */}
                <div style={styles.designTypeBox}>
                  <div style={styles.designTypeBoxHeader}>
                    <span style={styles.sharpBadge}>Sharp RDD</span>
                    {!isFuzzy && <span style={styles.designTypeCurrentTag}>✓ Current</span>}
                  </div>
                  <p style={styles.designTypeText}>
                    The cutoff rule is <strong>perfectly enforced</strong>. Every unit at or above the cutoff receives the treatment; every unit below does not. Treatment status is a deterministic step function of the running variable.
                  </p>
                  <ul style={styles.designTypeList}>
                    <li>Assignment ≡ receipt of treatment</li>
                    <li>Estimated directly as the discontinuity in the outcome</li>
                    <li>Example: scholarship eligibility tied to a hard GPA cutoff</li>
                  </ul>
                  <div style={{ marginTop: '12px', padding: '10px', backgroundColor: '#e8f5e9', borderRadius: '6px', fontSize: '13px', color: '#1b5e20' }}>
                    ✓ This is what the current analysis assumes and estimates.
                  </div>
                </div>

                {/* Fuzzy column */}
                <div style={{ ...styles.designTypeBox, borderColor: isFuzzy ? '#4F9CF9' : '#dee2e6', backgroundColor: isFuzzy ? '#f0f7ff' : '#fafafa' }}>
                  <div style={styles.designTypeBoxHeader}>
                    <span style={styles.fuzzyBadge}>Fuzzy RDD</span>
                    {isFuzzy && <span style={styles.designTypeCurrentTag}>✓ Current</span>}
                  </div>
                  <p style={styles.designTypeText}>
                    The cutoff only <strong>probabilistically determines</strong> treatment. Some units above the cutoff may not receive treatment; some below may still receive it. The cutoff is suggestive, not binding.
                  </p>
                  <ul style={styles.designTypeList}>
                    <li>Assignment ≠ receipt of treatment (non-compliance)</li>
                    <li>Uses a Wald formula: (jump in outcome) ÷ (jump in treatment rate) — analogous to an IV/LATE estimator</li>
                    <li>Requires a separate treatment-status variable in your data</li>
                    <li>Example: minimum drinking age — crossing 21 raises the probability of drinking, but doesn't guarantee it</li>
                  </ul>
                  <div style={{ marginTop: '12px', padding: '10px', backgroundColor: '#fff3cd', borderRadius: '6px', fontSize: '13px', color: '#856404' }}>
                    ⚠ If treatment receipt in your study is imperfect, Fuzzy RDD is more appropriate. The replication code can be extended by adding a first-stage regression.
                  </div>
                </div>

                {isFuzzy ? (
                  <div style={{ gridColumn: '1 / -1', padding: '14px 16px', backgroundColor: '#e8f5e9', borderRadius: '8px', border: '1px solid #4caf50', fontSize: '13px', color: '#1b5e20', lineHeight: 1.6 }}>
                    ✓ <strong>Fuzzy RDD was applied.</strong> The LATE was estimated as the Wald ratio: the jump in <em>{parameters.outcome_var}</em> at the cutoff divided by the jump in <em>{parameters.treatment_var}</em> at the cutoff. See the First-Stage diagnostics below for compliance details.
                  </div>
                ) : (
                  <div style={{ gridColumn: '1 / -1', padding: '14px 16px', backgroundColor: '#f0f7ff', borderRadius: '8px', border: '1px solid #b3d4f7', fontSize: '13px', color: '#043873', lineHeight: 1.6 }}>
                    <strong>Not sure which to use?</strong> Check whether all units {parameters.treatment_side === 'above' ? 'at or above' : 'below'} the cutoff ({parameters.cutoff}) actually received the treatment in your data. If compliance is perfect (or very close), Sharp RDD is appropriate. If a meaningful share did not comply, re-run the analysis selecting Fuzzy RDD with a treatment receipt variable.
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Warnings */}
          {(res.warnings && res.warnings.length > 0) ||
            (bandwidth_info.bandwidth_warnings && bandwidth_info.bandwidth_warnings.length > 0) ? (
            <div style={styles.warningCard}>
              <h3 style={styles.warningTitle}>⚠️ Warnings</h3>
              <ul style={styles.warningList}>
                {res.warnings &&
                  res.warnings.map((warning: string, idx: number) => (
                    <li key={`warn-${idx}`}>{warning}</li>
                  ))}
                {bandwidth_info.bandwidth_warnings &&
                  bandwidth_info.bandwidth_warnings.map(
                    (warning: string, idx: number) => (
                      <li key={`bw-warn-${idx}`}>{warning}</li>
                    )
                  )}
              </ul>
            </div>
          ) : null}

          

          {/* Sensitivity Analysis Visualization */}
          <RDSensitivityPlot
            datasetId={results.dataset_id}
            runningVar={parameters.running_var}
            outcomeVar={parameters.outcome_var}
            cutoff={parameters.cutoff}
            optimalBandwidth={bandwidth_info.optimal_bandwidth}
            treatmentSide={parameters.treatment_side}
          />

          {/* ── Reproducible Code Section ── */}
          <div style={styles.codeSection}>
            <div style={styles.codeSectionHeader}>
              <h2 style={styles.sectionTitle}>📝 Reproduce This Analysis</h2>
              <button
                onClick={() => setShowCode(!showCode)}
                style={styles.codeToggleButton}
              >
                {showCode ? '▲ Hide Code' : '▼ Show Code'}
              </button>
            </div>
            {showCode && (
              <div style={styles.codeContent}>
                <p style={styles.codeDescription}>
                  Use the code below to replicate this analysis and visualizations in your own environment.
                </p>
                <div style={styles.languageTabs}>
                  <button
                    onClick={() => setCodeLanguage('python')}
                    style={{
                      ...styles.languageTab,
                      ...(codeLanguage === 'python' ? styles.languageTabActive : {}),
                    }}
                  >
                    🐍 Python
                  </button>
                  <button
                    onClick={() => setCodeLanguage('r')}
                    style={{
                      ...styles.languageTab,
                      ...(codeLanguage === 'r' ? styles.languageTabActive : {}),
                    }}
                  >
                    📊 R
                  </button>
                </div>
                <div style={styles.codeBlock}>
                  <div style={styles.codeBlockHeader}>
                    <span style={styles.codeBlockTitle}>
                      {codeLanguage === 'python' ? 'Python (rdrobust)' : 'R (rdrobust)'}
                    </span>
                    <button
                      onClick={() => {
                        const code = codeLanguage === 'python' ? generatePythonCode() : generateRCode();
                        navigator.clipboard.writeText(code);
                        alert('Code copied to clipboard!');
                      }}
                      style={styles.copyButton}
                    >
                      📋 Copy Code
                    </button>
                  </div>
                  <pre style={styles.codeText}>
                    <code>{codeLanguage === 'python' ? generatePythonCode() : generateRCode()}</code>
                  </pre>
                </div>
              </div>
            )}
          </div>

        </div>
          </div>

          {/* AI Sidebar */}
          {!isAiSidebarCollapsed && (
            <div
              style={{
                ...styles.aiSidebar,
                width: `${aiSidebarWidth}px`,
                flex: `0 0 ${aiSidebarWidth}px`,
                position: 'sticky' as const,
                top: '90px',
                right: '0px',
                overflow: 'visible' as const,
                maxHeight: 'calc(100vh - 200px)',
                marginTop: '90px',
              }}
            >
              <div
                onMouseDown={handleResizeStart}
                style={{
                  position: 'absolute',
                  left: '-4px',
                  top: 0,
                  bottom: 0,
                  width: '8px',
                  cursor: 'col-resize',
                  zIndex: 10,
                  backgroundColor: isResizing ? 'rgba(79, 156, 249, 0.3)' : 'transparent',
                  borderLeft: isResizing ? '2px solid #4F9CF9' : 'none',
                }}
                title="Drag to resize"
              />
              <div
                style={{
                  ...styles.aiSection,
                  maxHeight: 'calc(100vh - 200px)',
                  overflowY: 'auto' as const,
                  overflowX: 'hidden' as const,
                  boxSizing: 'border-box' as const,
                }}
              >
                <div style={styles.aiSectionHeader}>
                  <h2 style={styles.sectionTitle}>🤖 AI-Powered Interpretation</h2>
                  {!aiInterpretation && !loadingAI && (
                    <button onClick={loadAIInterpretation} style={styles.getAiButton} disabled={loadingAI}>
                      ✨ Get AI Interpretation
                    </button>
                  )}
                </div>

                {loadingAI && (
                  <div style={styles.aiLoading}>
                    <div style={styles.aiSpinner}></div>
                    <p>AI is analyzing your results...</p>
                  </div>
                )}

                {aiError && !loadingAI && (
                  <div style={styles.aiError}>
                    <p>⚠️ {aiError}</p>
                    <p style={styles.aiErrorNote}>Your results are still valid. AI interpretation is temporarily unavailable.</p>
                    {!aiError.includes('quota exceeded') && (
                      <button onClick={() => { setAiError(null); loadAIInterpretation(); }} style={styles.retryButton}>
                        Try Again
                      </button>
                    )}
                  </div>
                )}

                {!loadingAI && !aiInterpretation && !aiError && (
                  <div style={styles.aiPrompt}>
                    <h3 style={styles.aiPromptTitle}>Get Expert Analysis</h3>
                    <p style={styles.aiPromptText}>
                      Click the button above to get AI-powered insights including executive summary,
                      effect size interpretation, bandwidth assessment, limitations, and actionable recommendations.
                    </p>
                  </div>
                )}

                {aiInterpretation && !loadingAI && (
                  <>
                    <div style={styles.aiCard}>
                      <h3 style={styles.aiCardTitle}>Executive Summary</h3>
                      <p style={styles.aiText}>{aiInterpretation.executive_summary}</p>
                    </div>
                    {aiInterpretation.parallel_trends_interpretation && (
                      <div style={styles.aiCard}>
                        <h3 style={styles.aiCardTitle}>Bandwidth & Design Assessment</h3>
                        <p style={styles.aiText}>{aiInterpretation.parallel_trends_interpretation}</p>
                      </div>
                    )}
                    {aiInterpretation.effect_size_interpretation && (
                      <div style={styles.aiCard}>
                        <h3 style={styles.aiCardTitle}>Effect Size</h3>
                        <p style={styles.aiText}>{aiInterpretation.effect_size_interpretation}</p>
                      </div>
                    )}
                    {aiInterpretation.statistical_interpretation && (
                      <div style={styles.aiCard}>
                        <h3 style={styles.aiCardTitle}>Statistical Significance</h3>
                        <p style={styles.aiText}>{aiInterpretation.statistical_interpretation}</p>
                      </div>
                    )}
                    {aiInterpretation.limitations && aiInterpretation.limitations.length > 0 && (
                      <div style={{ ...styles.aiCard, ...styles.aiCardWarning }}>
                        <h3 style={styles.aiCardTitle}>⚠️ Limitations & Caveats</h3>
                        <ul style={styles.aiList}>
                          {aiInterpretation.limitations.map((limit, i) => (
                            <li key={i} style={styles.aiListItem}>{limit}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                    {aiInterpretation.implications && aiInterpretation.implications.length > 0 && (
                      <div style={{ ...styles.aiCard, ...styles.aiCardSuccess }}>
                        <h3 style={styles.aiCardTitle}>💡 Practical Implications</h3>
                        <ul style={styles.aiList}>
                          {aiInterpretation.implications.map((imp, i) => (
                            <li key={i} style={styles.aiListItem}>{imp}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                    {aiInterpretation.next_steps && aiInterpretation.next_steps.length > 0 && (
                      <div style={{ ...styles.aiCard, ...styles.aiCardNextSteps }}>
                        <h3 style={styles.aiCardTitle}>🚀 Recommended Next Steps</h3>
                        <ul style={styles.aiList}>
                          {aiInterpretation.next_steps.map((step, i) => (
                            <li key={i} style={styles.aiListItem}>
                              <span style={styles.stepNumber}>{i + 1}</span>
                              {step}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                    {aiInterpretation.recommendation && (
                      <div style={{ ...styles.aiCard, ...styles.aiCardRecommendation }}>
                        <h3 style={styles.aiCardTitle}>📋 Bottom Line</h3>
                        <p style={styles.aiText}>{aiInterpretation.recommendation}</p>
                        {aiInterpretation.confidence_level && (
                          <p style={styles.confidenceLevel}>
                            Analysis Confidence: <strong style={{
                              color: aiInterpretation.confidence_level === 'high' ? '#28a745' :
                                aiInterpretation.confidence_level === 'medium' ? '#ffc107' : '#dc3545',
                            }}>{aiInterpretation.confidence_level.toUpperCase()}</strong>
                          </p>
                        )}
                      </div>
                    )}
                  </>
                )}

                {/* Ask AI Chat */}
                <div style={{ marginTop: '24px', borderTop: '2px solid #e9ecef', paddingTop: '20px' }}>
                  <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#043873', margin: '0 0 16px 0' }}>
                    💬 Ask AI
                  </h3>
                  <p style={{ fontSize: '13px', color: '#666', marginBottom: '16px', lineHeight: 1.5 }}>
                    Ask questions about your study, dataset, or causal inference concepts.
                  </p>

                  <div style={{
                    maxHeight: '400px',
                    overflowY: 'auto' as const,
                    marginBottom: '16px',
                    padding: '12px',
                    backgroundColor: '#f8f9fa',
                    borderRadius: '8px',
                    border: '1px solid #e9ecef',
                    minHeight: '200px',
                  }}>
                    {chatMessages.length === 0 ? (
                      <div style={{ textAlign: 'center' as const, color: '#999', padding: '40px 20px', fontSize: '14px' }}>
                        Start a conversation by asking a question below.
                      </div>
                    ) : (
                      chatMessages.map((msg, idx) => (
                        <div
                          key={idx}
                          style={{
                            marginBottom: '16px',
                            display: 'flex',
                            flexDirection: 'column' as const,
                            alignItems: msg.role === 'user' ? 'flex-end' : 'flex-start',
                          }}
                        >
                          <div style={{
                            maxWidth: '85%',
                            padding: '10px 14px',
                            borderRadius: '12px',
                            backgroundColor: msg.role === 'user' ? '#4F9CF9' : '#ffffff',
                            color: msg.role === 'user' ? '#ffffff' : '#333',
                            fontSize: '14px',
                            lineHeight: 1.5,
                            boxShadow: msg.role === 'user' ? 'none' : '0 1px 3px rgba(0,0,0,0.1)',
                            border: msg.role === 'user' ? 'none' : '1px solid #e9ecef',
                            whiteSpace: 'pre-wrap' as const,
                            wordBreak: 'break-word' as const,
                          }}>
                            {msg.content}
                          </div>
                        </div>
                      ))
                    )}
                    {chatLoading && (
                      <div style={{ display: 'flex', alignItems: 'flex-start', marginBottom: '16px' }}>
                        <div style={{
                          padding: '10px 14px',
                          borderRadius: '12px',
                          backgroundColor: '#ffffff',
                          border: '1px solid #e9ecef',
                          fontSize: '14px',
                          color: '#666',
                          display: 'flex',
                          alignItems: 'center',
                        }}>
                          <div style={{
                            width: '16px',
                            height: '16px',
                            border: '2px solid #f3f3f3',
                            borderTop: '2px solid #4F9CF9',
                            borderRadius: '50%',
                            animation: 'spin 1s linear infinite',
                            marginRight: '8px',
                          }} />
                          <span>AI is thinking...</span>
                        </div>
                      </div>
                    )}
                    <div ref={chatMessagesEndRef} />
                  </div>

                  {chatError && (
                    <div style={{
                      padding: '10px',
                      marginBottom: '12px',
                      backgroundColor: '#f8d7da',
                      color: '#721c24',
                      borderRadius: '6px',
                      fontSize: '13px',
                      border: '1px solid #f5c6cb',
                    }}>
                      ⚠️ {chatError}
                    </div>
                  )}

                  <div style={{ display: 'flex', gap: '8px', alignItems: 'flex-end' }}>
                    <textarea
                      value={chatInput}
                      onChange={(e) => {
                        const v = e.target.value;
                        if (v.length <= MAX_MESSAGE_LENGTH) {
                          setChatInput(v);
                          setChatError(null);
                        }
                      }}
                      onKeyPress={handleChatInputKeyPress}
                      placeholder="Ask a question about your analysis..."
                      disabled={chatLoading}
                      style={{
                        flex: 1,
                        minHeight: '60px',
                        maxHeight: '120px',
                        padding: '10px 12px',
                        borderRadius: '8px',
                        border: '1px solid #dee2e6',
                        fontSize: '14px',
                        fontFamily: 'inherit',
                        resize: 'vertical' as const,
                        outline: 'none',
                        boxSizing: 'border-box' as const,
                      }}
                    />
                    <button
                      onClick={handleSendMessage}
                      disabled={!chatInput.trim() || chatLoading || chatInput.length > MAX_MESSAGE_LENGTH}
                      style={{
                        padding: '10px 20px',
                        backgroundColor: chatInput.trim() && !chatLoading && chatInput.length <= MAX_MESSAGE_LENGTH ? '#4F9CF9' : '#ccc',
                        color: '#ffffff',
                        border: 'none',
                        borderRadius: '8px',
                        cursor: chatInput.trim() && !chatLoading && chatInput.length <= MAX_MESSAGE_LENGTH ? 'pointer' : 'not-allowed',
                        fontSize: '14px',
                        fontWeight: 600,
                        height: '60px',
                        minWidth: '80px',
                      }}
                    >
                      {chatLoading ? '...' : 'Send'}
                    </button>
                  </div>
                  <div style={{ fontSize: '12px', color: '#999', marginTop: '6px', textAlign: 'right' as const }}>
                    {chatInput.length}/{MAX_MESSAGE_LENGTH} characters
                  </div>

                  {recommendedQuestions.length > 0 && (
                    <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: '1px solid #e9ecef' }}>
                      <div style={{ fontSize: '13px', color: '#666', marginBottom: '10px', fontWeight: 500 }}>
                        💡 Suggested questions:
                      </div>
                      <div style={{ display: 'flex', flexDirection: 'column' as const, gap: '8px' }}>
                        {recommendedQuestions.map((q, idx) => (
                          <button
                            key={idx}
                            onClick={() => {
                              setChatInput(q);
                              setChatError(null);
                              setTimeout(() => {
                                const ta = document.querySelector('textarea[placeholder*="Ask a question"]') as HTMLTextAreaElement;
                                if (ta) {
                                  ta.focus();
                                  ta.setSelectionRange(q.length, q.length);
                                }
                              }, 0);
                            }}
                            disabled={chatLoading}
                            style={{
                              padding: '10px 14px',
                              backgroundColor: '#f8f9fa',
                              border: '1px solid #dee2e6',
                              borderRadius: '8px',
                              fontSize: '13px',
                              color: '#043873',
                              cursor: chatLoading ? 'not-allowed' : 'pointer',
                              textAlign: 'left' as const,
                              opacity: chatLoading ? 0.6 : 1,
                            }}
                          >
                            {q}
                          </button>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          {isAiSidebarCollapsed && (
            <button
              onClick={handleOpenAiSection}
              style={{
                position: 'fixed',
                right: 0,
                top: '50%',
                transform: 'translateY(-50%)',
                width: '60px',
                height: '220px',
                backgroundColor: '#4F9CF9',
                color: '#ffffff',
                border: 'none',
                borderRadius: '8px 0 0 8px',
                cursor: 'pointer',
                display: 'flex',
                flexDirection: 'column' as const,
                alignItems: 'center',
                justifyContent: 'center',
                gap: '12px',
                boxShadow: '-4px 0 12px rgba(79, 156, 249, 0.3)',
                zIndex: 1000,
                padding: '20px 10px',
              }}
              title="Show AI Interpretation"
              type="button"
            >
              <span style={{ fontSize: '14px', fontWeight: 600, writingMode: 'vertical-rl', textOrientation: 'mixed', letterSpacing: '1px' }}>
                Open AI section
              </span>
            </button>
          )}
        </div>
      </div>
      <BottomProgressBar
        currentStep={currentStep}
        steps={steps}
        onPrev={goToPreviousStep}
        onNext={goToNextStep}
        canGoNext={false}
        onStepClick={(stepPath) => navigateToStep(stepPath)}
      />
    </div>
  );
};

export default RDResults;

const styles = {
  contentContainer: {
    paddingTop: '70px',
    paddingBottom: '120px',
    minHeight: 'calc(100vh - 70px)',
    backgroundColor: '#f5f5f5',
  },
  mainLayout: {
    display: 'flex',
    gap: '24px',
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '20px 10px',
    width: '100%',
    boxSizing: 'border-box' as const,
    alignItems: 'flex-start',
    position: 'relative' as const,
  },
  mainContent: {
    flex: '1 1 0',
    minWidth: 0,
    boxSizing: 'border-box' as const,
  },
  aiSidebar: {
    width: '420px',
    maxHeight: 'calc(100vh - 110px)',
    overflowY: 'auto' as const,
    overflowX: 'hidden' as const,
    boxSizing: 'border-box' as const,
    transition: 'all 0.3s ease',
  },
  container: {
    paddingTop: '70px',
    paddingBottom: '100px',
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 'calc(100vh - 70px)',
    backgroundColor: '#f5f5f5',
  },
  loadingSpinner: {
    width: '40px',
    height: '40px',
    border: '4px solid #f3f3f3',
    borderTop: '4px solid #043873',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
    marginBottom: '20px',
  },
  loadingText: {
    fontSize: '18px',
    color: '#666',
    margin: 0,
  },
  errorContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 'calc(100vh - 70px)',
    backgroundColor: '#f5f5f5',
    padding: '40px 20px',
    textAlign: 'center' as const,
  },
  errorTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#dc3545',
    margin: '0 0 15px 0',
  },
  errorMessage: {
    fontSize: '16px',
    color: '#666',
    margin: '0 0 30px 0',
    maxWidth: '500px',
    lineHeight: '1.5',
  },
  backButton: {
    backgroundColor: '#043873',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    padding: '12px 24px',
    fontSize: '16px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  header: {
    textAlign: 'center' as const,
    padding: '40px 20px 30px',
    maxWidth: '1000px',
    margin: '0 auto',
  },
  title: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#333',
    margin: '0 0 10px 0',
  },
  subtitle: {
    fontSize: '16px',
    color: '#666',
    margin: 0,
  },
  content: {
    maxWidth: '900px',
    margin: '0 auto',
    padding: '0 20px 40px',
  },
  mainResultCard: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '40px',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
    textAlign: 'center' as const,
    marginBottom: '30px',
  },
  resultLabel: {
    fontSize: '18px',
    fontWeight: '600',
    color: '#666',
    margin: '0 0 15px 0',
  },
  effectValue: {
    fontSize: '48px',
    fontWeight: 'bold',
    color: '#043873',
    margin: '0 0 15px 0',
  },
  significanceBadge: {
    display: 'block',
    padding: '10px 20px',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    marginBottom: '8px',
  },
  significantBadge: {
    backgroundColor: '#d4edda',
    color: '#155724',
  },
  notSignificantBadge: {
    backgroundColor: '#f8d7da',
    color: '#721c24',
  },
  statsRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '24px',
    marginTop: '24px',
    paddingTop: '20px',
    borderTop: '1px solid #eee',
    justifyContent: 'center',
  },
  statRowItem: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    minWidth: '200px',
  },
  statRowLabel: {
    fontSize: '14px',
    color: '#666',
    marginBottom: '4px',
  },
  statRowValue: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#043873',
    marginBottom: '8px',
  },
  expandButton: {
    padding: '4px 10px',
    backgroundColor: 'transparent',
    color: '#043873',
    border: '1px solid #043873',
    borderRadius: '6px',
    fontSize: '12px',
    cursor: 'pointer',
    textAlign: 'center' as const,
  },
  expandButtonActive: {
    padding: '4px 10px',
    backgroundColor: '#043873',
    color: '#fff',
    border: '1px solid #043873',
    borderRadius: '6px',
    fontSize: '12px',
    cursor: 'pointer',
    textAlign: 'center' as const,
  },
  singleExplanationBox: {
    marginTop: '16px',
    padding: '16px 20px',
    backgroundColor: '#f8f9fa',
    borderRadius: '10px',
    border: '1px solid #e9ecef',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  singleExplanationText: {
    margin: 0,
    fontSize: '14px',
    color: '#333',
    lineHeight: 1.6,
    textAlign: 'left' as const,
  },
  bandwidthExplanation: {
    margin: '20px 0 0 0',
    padding: '16px',
    backgroundColor: '#f8f9fa',
    borderRadius: '8px',
    fontSize: '14px',
    color: '#333',
    lineHeight: 1.6,
    borderTop: '1px solid #eee',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '20px',
    marginBottom: '30px',
  },
  statCard: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '25px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    textAlign: 'center' as const,
  },
  statLabel: {
    fontSize: '14px',
    color: '#666',
    marginBottom: '10px',
  },
  statValue: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#043873',
  },
  infoCard: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '30px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    marginBottom: '30px',
  },
  infoTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#333',
    margin: '0 0 20px 0',
  },
  infoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '15px',
  },
  infoItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '12px',
    backgroundColor: '#f8f9fa',
    borderRadius: '8px',
  },
  infoLabel: {
    fontSize: '14px',
    color: '#666',
    fontWeight: '500',
  },
  infoValue: {
    fontSize: '14px',
    color: '#333',
    fontWeight: '600',
  },
  warningCard: {
    backgroundColor: '#fff3cd',
    border: '1px solid #ffc107',
    borderRadius: '12px',
    padding: '25px',
    marginBottom: '30px',
  },
  warningTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#856404',
    margin: '0 0 15px 0',
  },
  warningList: {
    margin: 0,
    paddingLeft: '20px',
    color: '#856404',
    lineHeight: '1.6',
  },
  // AI Interpretation styles
  aiSection: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '24px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
    border: '1px solid #e0e0e0',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  aiSectionHeader: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    marginBottom: '20px',
  },
  sectionTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#043873',
    margin: 0,
  },
  getAiButton: {
    backgroundColor: '#6366f1',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  aiLoading: {
    textAlign: 'center' as const,
    padding: '40px',
  },
  aiSpinner: {
    width: '40px',
    height: '40px',
    border: '4px solid #f3f3f3',
    borderTop: '4px solid #4F9CF9',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
    margin: '0 auto 16px',
  },
  aiError: {
    backgroundColor: '#f8d7da',
    color: '#721c24',
    padding: '20px',
    borderRadius: '8px',
    border: '1px solid #f5c6cb',
  },
  aiErrorNote: {
    fontSize: '14px',
    marginTop: '8px',
    opacity: 0.9,
  },
  retryButton: {
    backgroundColor: '#6c757d',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    marginTop: '12px',
  },
  aiPrompt: {
    textAlign: 'center' as const,
    padding: '40px',
  },
  aiPromptTitle: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#333',
    margin: '0 0 8px 0',
  },
  aiPromptText: {
    fontSize: '14px',
    color: '#666',
    lineHeight: '1.6',
    margin: '0 auto',
  },
  aiCard: {
    backgroundColor: '#f8f9fa',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '16px',
    border: '1px solid #e9ecef',
    borderLeft: '4px solid #4F9CF9',
  },
  aiCardWarning: {
    backgroundColor: '#fff3cd',
    border: '1px solid #ffc107',
  },
  aiCardSuccess: {
    backgroundColor: '#d4edda',
    border: '1px solid #28a745',
  },
  aiCardNextSteps: {
    backgroundColor: '#e8f5e9',
    border: '1px solid #4caf50',
  },
  aiCardRecommendation: {
    backgroundColor: '#e3f2fd',
    borderLeft: '4px solid #2196f3',
  },
  aiCardTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#043873',
    margin: '0 0 12px 0',
  },
  aiText: {
    fontSize: '16px',
    lineHeight: '1.6',
    color: '#333',
    margin: 0,
  },
  aiList: {
    margin: '10px 0',
    paddingLeft: '20px',
  },
  aiListItem: {
    fontSize: '14px',
    lineHeight: '1.6',
    color: '#333',
    marginBottom: '6px',
  },
  stepNumber: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
    height: '24px',
    backgroundColor: '#4caf50',
    color: 'white',
    borderRadius: '50%',
    marginRight: '8px',
    fontSize: '12px',
    fontWeight: 600,
  },
  confidenceLevel: {
    marginTop: '15px',
    fontSize: '14px',
    color: '#666',
    fontStyle: 'italic',
  },
  // ── Code Section Styles ───────────────────────────────────────────────────
  codeSection: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '30px 40px',
    marginBottom: '30px',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
    border: '1px solid #e9ecef',
  },
  codeSectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  codeToggleButton: {
    backgroundColor: '#f8f9fa',
    color: '#212529',
    border: '1px solid #dee2e6',
    borderRadius: '8px',
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: '600' as const,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  codeContent: {
    marginTop: '20px',
  },
  codeDescription: {
    fontSize: '15px',
    color: '#666',
    marginBottom: '20px',
    lineHeight: '1.6',
  },
  languageTabs: {
    display: 'flex',
    gap: '10px',
    marginBottom: '15px',
  },
  languageTab: {
    backgroundColor: '#f8f9fa',
    color: '#212529',
    border: '2px solid #e9ecef',
    borderRadius: '8px',
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: '600' as const,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  languageTabActive: {
    backgroundColor: '#043873',
    color: 'white',
    borderColor: '#043873',
  },
  codeBlock: {
    backgroundColor: '#1e1e1e',
    borderRadius: '12px',
    overflow: 'hidden' as const,
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
  },
  codeBlockHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 20px',
    backgroundColor: '#2d2d2d',
    borderBottom: '1px solid #3d3d3d',
  },
  codeBlockTitle: {
    color: '#9cdcfe',
    fontSize: '13px',
    fontWeight: '600' as const,
  },
  copyButton: {
    backgroundColor: '#4F9CF9',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    padding: '8px 14px',
    fontSize: '13px',
    fontWeight: '600' as const,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  codeText: {
    margin: 0,
    padding: '20px',
    fontSize: '13px',
    lineHeight: '1.6',
    color: '#d4d4d4',
    overflow: 'auto' as const,
    maxHeight: '500px',
    fontFamily: "'Fira Code', 'Consolas', 'Monaco', monospace",
  },

  // ── Fuzzy RDD badge ──────────────────────────────────────────────────────
  fuzzyBadge: {
    display: 'inline-block',
    padding: '3px 10px',
    backgroundColor: '#fff3cd',
    color: '#856404',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: '600' as const,
  },

  // ── Fuzzy first-stage compliance card ────────────────────────────────────
  fuzzyCard: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '28px 36px',
    marginBottom: '30px',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
    border: '1px solid #e9ecef',
    borderTop: '4px solid #ffc107',
  },
  fuzzyCardTitle: {
    fontSize: '20px',
    fontWeight: 'bold' as const,
    color: '#043873',
    margin: '0 0 8px 0',
  },
  fuzzyGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '14px',
  },
  fuzzyStatBox: {
    padding: '16px',
    backgroundColor: '#f8f9fa',
    borderRadius: '10px',
    border: '1px solid #e9ecef',
  },
  fuzzyStatLabel: {
    fontSize: '12px',
    color: '#666',
    marginBottom: '6px',
    fontWeight: '600' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.4px',
  },
  fuzzyStatValue: {
    fontSize: '22px',
    fontWeight: 'bold' as const,
    color: '#043873',
    marginBottom: '4px',
  },
  fuzzyStatNote: {
    fontSize: '11px',
    color: '#888',
    lineHeight: 1.4,
  },

  // ── Assumptions card ─────────────────────────────────────────────────────
  assumptionsCard: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '28px 36px',
    marginBottom: '30px',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
    border: '1px solid #e9ecef',
    borderTop: '4px solid #6366f1',
  },
  assumptionsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  assumptionsTitle: {
    fontSize: '20px',
    fontWeight: 'bold' as const,
    color: '#043873',
    margin: 0,
  },
  assumptionsSub: {
    fontSize: '14px',
    color: '#666',
    margin: 0,
    lineHeight: 1.5,
  },
  assumptionsToggle: {
    backgroundColor: '#f8f9fa',
    color: '#212529',
    border: '1px solid #dee2e6',
    borderRadius: '8px',
    padding: '8px 18px',
    fontSize: '13px',
    fontWeight: '600' as const,
    cursor: 'pointer',
  },
  sharpBadge: {
    display: 'inline-block',
    padding: '3px 10px',
    backgroundColor: '#e8f5e9',
    color: '#1b5e20',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: '600' as const,
  },
  assumptionTabs: {
    display: 'flex',
    gap: '8px',
    marginBottom: '20px',
    flexWrap: 'wrap' as const,
  },
  assumptionTab: {
    backgroundColor: '#f8f9fa',
    color: '#495057',
    border: '2px solid #e9ecef',
    borderRadius: '8px',
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: '600' as const,
    cursor: 'pointer',
  },
  assumptionTabActive: {
    backgroundColor: '#6366f1',
    color: 'white',
    borderColor: '#6366f1',
  },
  assumptionContent: {
    padding: '20px',
    backgroundColor: '#f8f9fa',
    borderRadius: '12px',
    border: '1px solid #e9ecef',
  },
  assumptionContentTitle: {
    fontSize: '16px',
    fontWeight: 'bold' as const,
    color: '#043873',
    margin: '0 0 12px 0',
  },
  assumptionText: {
    fontSize: '14px',
    color: '#333',
    lineHeight: 1.7,
    margin: '0 0 12px 0',
  },
  assumptionTip: {
    display: 'flex',
    gap: '10px',
    alignItems: 'flex-start',
    padding: '12px 14px',
    backgroundColor: '#e8f4fd',
    borderRadius: '8px',
    border: '1px solid #b3d4f7',
    fontSize: '13px',
    color: '#1a4a7a',
    lineHeight: 1.6,
  },
  // ── Sharp vs Fuzzy RDD card ───────────────────────────────────────────────
  designTypeCard: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '28px 36px',
    marginBottom: '30px',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
    border: '1px solid #e9ecef',
    borderTop: '4px solid #043873',
  },
  designTypeHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '6px',
  },
  designTypeTitle: {
    fontSize: '18px',
    fontWeight: 'bold' as const,
    color: '#043873',
    margin: 0,
  },
  designTypeCurrentTag: {
    fontSize: '12px',
    fontWeight: '600' as const,
    color: '#1b5e20',
    backgroundColor: '#e8f5e9',
    padding: '2px 8px',
    borderRadius: '4px',
  },
  designTypeBox: {
    padding: '20px',
    backgroundColor: '#f0f7ff',
    borderRadius: '10px',
    border: '2px solid #4F9CF9',
  },
  designTypeBoxHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '12px',
  },
  designTypeText: {
    fontSize: '14px',
    color: '#333',
    lineHeight: 1.6,
    margin: '0 0 10px 0',
  },
  designTypeList: {
    margin: '0',
    paddingLeft: '18px',
    fontSize: '13px',
    color: '#444',
    lineHeight: 1.8,
  },
};

