"""Initial migration - users, projects, datasets, analyses

Revision ID: 1303481df016
Revises: 
Create Date: 2025-12-04 00:31:04.989723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1303481df016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Tables already exist in database. This migration is marked as applied.
    # If you need to modify schema, create a new migration after this one.
    # 
    # Original migration attempted to:
    # - Drop completed_at and created_at from analyses
    # - Drop created_at from projects  
    # - Modify created_at columns in datasets and users
    #
    # Since tables already exist and user lacks ownership permissions,
    # this migration is a no-op. Schema changes should be done in future migrations.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: This migration is a no-op since tables already exist.
    # Downgrade is also a no-op to maintain migration history.
    pass
    # ### end Alembic commands ###
